version: 0.0
os: linux
files:
  - source: Health_Care
    destination: /home/ec2-user/x22146962-healthcare
hooks:
  BeforeInstall:
      - location: scripts/before_install.sh

  AfterInstall:
      - location: scripts/after_install.sh