version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade pip
      # Install dependencies needed for running the static analysis
      - pip install -r requirements.txt pylint
  pre_build:
    commands:
      - python --version
      - pylint -- $cloud_project/*.py
      # - pylint -- $CODEBUILD_SRC_DIR/Health_Care/Health_Care_app/*.py
artifacts:
  files:
    - '**/*'
