branch-defaults:
  main:
    environment: HealthCareX22146962tho-env
    group_suffix: null
global:
  application_name: HealthCareX22146962th0
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
