# Generated by Django 2.0.2 on 2023-04-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Health_Care_app', '0006_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='medical_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Health_Care_app.MedicalRecord'),
            preserve_default=False,
        ),
    ]
